### ISSUE TITLE
R support for fastquant

### ISSUE THREAD

**Issue by enzoampil** [enzoampil/fastquant#13] opened 2020-04-02 11:39 UTC

**Comment by jgendrinal** [comment] 2020-04-03 03:56
Will only close this issue after the first release of the R package

**Comment by jgendrinal** [comment] 2020-04-03 03:58
- [ ] Ensure that R and Python packages have the same features and tests
- [ ] Both R and Python packages build and pass all tests
- [ ] R package has an approved CRAN submission

**Comment by jgendrinal** [comment] 2020-06-30 18:15
Closing this issue, as this is an old duplicate of https://github.com/enzoampil/fastquant/issues/120

**Closed by jgendrinal** 2020-06-30 18:15 UTC
Labels: r-dev
