### ISSUE TITLE
[BUG] Incorrect interval displayed on backtesting result plot

### ISSUE THREAD

**Issue by ntakouris** [enzoampil/fastquant#337] opened 2021-01-25 15:47 UTC
#### Problem description
Backtest results plot does not infer input data time interval / time delta correctly and it just assumes that your data are on daily intervals. cc @enzoampil stated that it is a UI-issue only (on fastquant slack)

#### Example
[Look at this plot closely](https://files.slack.com/files-pri/T011P5D2SUV-F01KXSG410C/screenshot_20210125-154526_messenger.jpg), it says (1 Day) close, while it should say 1h or input dataframe interval.

#### Environment
Not Applicable

**Comment by mikeejazmines** [comment] 2021-12-16 06:01
Hi! If this issue persists please provide a way to replicate. We have just released a new version that handles intraday data as well

**Comment by jpdeleon** [comment] 2021-12-16 06:53
Since OP did not follow up with a code to reproduce the bug, I will close this issue for now. Please re-open this issue later if needed.

**Closed by jpdeleon** 2021-12-16 06:53 UTC
Labels: bug
